name: ETL workflow dor group 4

on:
  schedule:
    - cron: '5 * * * *' # Run every 1 hours
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("ggplot2","dplyr","readr","RSQLite"))'
      - name: Execute data validation
        run: |
          Rscript R/data_validation.R
      - name: Execute data analysis
        run: |
          Rscript R/load_data.R
        continue-on-error: true
      - name: Add files
        run: |
          git config --global user.email "u2292213@live.warwick.ac.uk"
          git config --global user.name "santiagocel"
          git add --all database/
      - name: Commit files
        run: |
          git commit -m "Updated database"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main

